/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie.graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import pharmacie.DAO.PatientDAO;

/**
 *
 * @author dorian.blumart
 */
public class GestionPharmacie extends javax.swing.JFrame {

    private CardLayout cl;

    /**
     * Creates new form GestionPharmacie
     */
    public GestionPharmacie() {       
        initComponents();
        //on va accèder au card layout
        cl = (CardLayout) this.getContentPane().getLayout();
        //c'est le panneau préenregistré sur lequel on ajoute les éléments, panneau invisible du jframe, il contient le layout
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this, "connexion invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

        PatientDAO patientDAO = new PatientDAO();
        patientDAO.setConnection(dbConnect);
        creaPatient.setPatientDAO(patientDAO);
        affPatient.setPatientDAO(patientDAO);
        rechPatNom.setPatientDAO(patientDAO);
        rechPatNum.setPatientDAO(patientDAO);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affPatient = new pharmacie.graph.AffPatient();
        creaPatient = new pharmacie.graph.CreaPatient();
        rechPatNom = new pharmacie.graph.RechPatNom();
        rechPatNum = new pharmacie.graph.RechPatNum();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPat = new javax.swing.JMenu();
        jMenuItemCrea = new javax.swing.JMenuItem();
        jMenuItemRechNum = new javax.swing.JMenuItem();
        jMenuItemRechNom = new javax.swing.JMenuItem();
        jMenuItemAff = new javax.swing.JMenuItem();
        jMenuPres = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(affPatient, "cardAffPat");
        getContentPane().add(creaPatient, "cardCreaPat");
        getContentPane().add(rechPatNom, "cardRechNomPat");
        getContentPane().add(rechPatNum, "cardRechNumPat");

        jMenuPat.setText("Patients");

        jMenuItemCrea.setText("Ajouter");
        jMenuItemCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreaActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemCrea);

        jMenuItemRechNum.setText("Recherche exacte (via id)");
        jMenuItemRechNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRechNumActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemRechNum);

        jMenuItemRechNom.setText("Recherche large (via nom)");
        jMenuItemRechNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRechNomActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemRechNom);

        jMenuItemAff.setText("Afficher totalité");
        jMenuItemAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAffActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemAff);

        jMenuBar1.add(jMenuPat);

        jMenuPres.setText("Prescriptions");
        jMenuBar1.add(jMenuPres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreaActionPerformed
        cl.show(this.getContentPane(), "cardCreaPat");  //on veut montrer la card ajout
    }//GEN-LAST:event_jMenuItemCreaActionPerformed

    private void jMenuItemAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAffActionPerformed
        cl.show(this.getContentPane(), "cardAffPat");  
    }//GEN-LAST:event_jMenuItemAffActionPerformed

    private void jMenuItemRechNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRechNumActionPerformed
        cl.show(this.getContentPane(), "cardRechNumPat");
    }//GEN-LAST:event_jMenuItemRechNumActionPerformed

    private void jMenuItemRechNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRechNomActionPerformed
        cl.show(this.getContentPane(), "cardRechNomPat");
    }//GEN-LAST:event_jMenuItemRechNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pharmacie.graph.AffPatient affPatient;
    private pharmacie.graph.CreaPatient creaPatient;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAff;
    private javax.swing.JMenuItem jMenuItemCrea;
    private javax.swing.JMenuItem jMenuItemRechNom;
    private javax.swing.JMenuItem jMenuItemRechNum;
    private javax.swing.JMenu jMenuPat;
    private javax.swing.JMenu jMenuPres;
    private pharmacie.graph.RechPatNom rechPatNom;
    private pharmacie.graph.RechPatNum rechPatNum;
    // End of variables declaration//GEN-END:variables
}
