/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacie.graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import pharmacie.DAO.InfosDAO;
import pharmacie.DAO.MedicamentDAO;
import pharmacie.DAO.PatientDAO;
import pharmacie.DAO.PrescriptionDAO;
import pharmacie.DAO.VUE_PRESCR_MEDOCDAO;
import pharmacie.DAO.VUE_QTOT_UNITE_MEDOCDAO;

/**
 *
 * @author dorian.blumart
 */
public class GestionPharmacie extends javax.swing.JFrame {

    private CardLayout cl;

    /**
     * Creates new form GestionPharmacie
     */
    public GestionPharmacie() {       
        initComponents();
        //on va accèder au card layout
        cl = (CardLayout) this.getContentPane().getLayout();
        //c'est le panneau préenregistré sur lequel on ajoute les éléments, panneau invisible du jframe, il contient le layout
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this, "connexion invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

        PatientDAO patientDAO = new PatientDAO();
        patientDAO.setConnection(dbConnect);
        creaPatient.setPatientDAO(patientDAO);
        affPatient.setPatientDAO(patientDAO);
        rechPatNom.setPatientDAO(patientDAO);
        rechPatNum.setPatientDAO(patientDAO);
        rechPresPat.setPatientDAO(patientDAO);
        
        VUE_PRESCR_MEDOCDAO vueDAO = new VUE_PRESCR_MEDOCDAO();
        vueDAO.setConnection(dbConnect);
        affPrescription.setVUE_PRESCR_MEDOCDAO(vueDAO);
        rechPresPat.setVUE_PRESCR_MEDOCDAO(vueDAO);
        
        PrescriptionDAO prescriptionDAO = new PrescriptionDAO();
        prescriptionDAO.setConnection(dbConnect);
        rechPresNum.setPrescriptionDAO(prescriptionDAO);
        creaPrescription.setPrescriptionDAO(prescriptionDAO);
        
        InfosDAO infosDAO = new InfosDAO();
        infosDAO.setConnection(dbConnect);
        rechPresNum.setInfosDAO(infosDAO);
        creaPrescription.setInfosDAO(infosDAO);
        
        MedicamentDAO medicamentDAO = new MedicamentDAO();
        medicamentDAO.setConnection(dbConnect);
        creaMedicament.setMedicamentDAO(medicamentDAO);
        rechMedocNum.setMedicamentDAO(medicamentDAO);
        rechMedocDesc.setMedicamentDAO(medicamentDAO);
        affMedoc.setMedicamentDAO(medicamentDAO);
        
        VUE_QTOT_UNITE_MEDOCDAO vue2DAO= new VUE_QTOT_UNITE_MEDOCDAO();
        vue2DAO.setConnection(dbConnect);
        affQuantMedoc.setVUE_QTOT_UNITE_MEDOCDAO(vue2DAO);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affPatient = new pharmacie.graph.AffPatient();
        creaPatient = new pharmacie.graph.CreaPatient();
        rechPatNom = new pharmacie.graph.RechPatNom();
        rechPatNum = new pharmacie.graph.RechPatNum();
        affPrescription = new pharmacie.graph.AffPrescription();
        rechPresNum = new pharmacie.graph.RechPresNum();
        rechPresPat = new pharmacie.graph.RechPresPat();
        creaPrescription = new pharmacie.graph.CreaPrescription();
        creaMedicament = new pharmacie.graph.CreaMedicament();
        rechMedocNum = new pharmacie.graph.RechMedocNum();
        rechMedocDesc = new pharmacie.graph.RechMedocDesc();
        affMedoc = new pharmacie.graph.AffMedoc();
        affQuantMedoc = new pharmacie.graph.AffQuantMedoc();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPat = new javax.swing.JMenu();
        jMenuItemCrea = new javax.swing.JMenuItem();
        jMenuItemRechNum = new javax.swing.JMenuItem();
        jMenuItemRechNom = new javax.swing.JMenuItem();
        jMenuItemAff = new javax.swing.JMenuItem();
        jMenuPres = new javax.swing.JMenu();
        jMenuCreaPres = new javax.swing.JMenuItem();
        jMenuRechNumPres = new javax.swing.JMenuItem();
        jMenuRechPatPres = new javax.swing.JMenuItem();
        jMenuAffPres = new javax.swing.JMenuItem();
        jMenuMedoc = new javax.swing.JMenu();
        jMenuCreaMedoc = new javax.swing.JMenuItem();
        jMenuRechNumMedoc = new javax.swing.JMenuItem();
        jMenuRechDescMedoc = new javax.swing.JMenuItem();
        jMenuAffQuantMedoc = new javax.swing.JMenuItem();
        jMenuAffMedoc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(affPatient, "cardAffPat");
        getContentPane().add(creaPatient, "cardCreaPat");
        getContentPane().add(rechPatNom, "cardRechNomPat");
        getContentPane().add(rechPatNum, "cardRechNumPat");
        getContentPane().add(affPrescription, "cardAffPres");
        getContentPane().add(rechPresNum, "cardRechNumPres");
        getContentPane().add(rechPresPat, "cardRechPatPres");
        getContentPane().add(creaPrescription, "cardCreaPres");
        getContentPane().add(creaMedicament, "cardCreaMedoc");
        getContentPane().add(rechMedocNum, "cardRechNumMedoc");
        getContentPane().add(rechMedocDesc, "cardRechDescMedoc");
        getContentPane().add(affMedoc, "cardAffMedoc");
        getContentPane().add(affQuantMedoc, "cardAffQuantMedoc");

        jMenuPat.setText("Patients");

        jMenuItemCrea.setText("Ajouter");
        jMenuItemCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreaActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemCrea);

        jMenuItemRechNum.setText("Recherche exacte (via id)");
        jMenuItemRechNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRechNumActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemRechNum);

        jMenuItemRechNom.setText("Recherche large (via nom)");
        jMenuItemRechNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRechNomActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemRechNom);

        jMenuItemAff.setText("Afficher totalité");
        jMenuItemAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAffActionPerformed(evt);
            }
        });
        jMenuPat.add(jMenuItemAff);

        jMenuBar1.add(jMenuPat);

        jMenuPres.setText("Prescriptions");

        jMenuCreaPres.setText("Ajouter");
        jMenuCreaPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreaPresActionPerformed(evt);
            }
        });
        jMenuPres.add(jMenuCreaPres);

        jMenuRechNumPres.setText("Recherche exacte (via id)");
        jMenuRechNumPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRechNumPresActionPerformed(evt);
            }
        });
        jMenuPres.add(jMenuRechNumPres);

        jMenuRechPatPres.setText("Recherche large (via patient)");
        jMenuRechPatPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRechPatPresActionPerformed(evt);
            }
        });
        jMenuPres.add(jMenuRechPatPres);

        jMenuAffPres.setText("Afficher totalité");
        jMenuAffPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAffPresActionPerformed(evt);
            }
        });
        jMenuPres.add(jMenuAffPres);

        jMenuBar1.add(jMenuPres);

        jMenuMedoc.setText("Médicaments");

        jMenuCreaMedoc.setText("Ajouter");
        jMenuCreaMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreaMedocActionPerformed(evt);
            }
        });
        jMenuMedoc.add(jMenuCreaMedoc);

        jMenuRechNumMedoc.setText("Recherche exacte (via id)");
        jMenuRechNumMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRechNumMedocActionPerformed(evt);
            }
        });
        jMenuMedoc.add(jMenuRechNumMedoc);

        jMenuRechDescMedoc.setText("Recherche large (via description)");
        jMenuRechDescMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRechDescMedocActionPerformed(evt);
            }
        });
        jMenuMedoc.add(jMenuRechDescMedoc);

        jMenuAffQuantMedoc.setText("Afficher les quantités écoulées (via id)");
        jMenuAffQuantMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAffQuantMedocActionPerformed(evt);
            }
        });
        jMenuMedoc.add(jMenuAffQuantMedoc);

        jMenuAffMedoc.setText("Afficher totalité");
        jMenuAffMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAffMedocActionPerformed(evt);
            }
        });
        jMenuMedoc.add(jMenuAffMedoc);

        jMenuBar1.add(jMenuMedoc);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreaActionPerformed
        cl.show(this.getContentPane(), "cardCreaPat");  //on veut montrer la card ajout
    }//GEN-LAST:event_jMenuItemCreaActionPerformed

    private void jMenuItemAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAffActionPerformed
        cl.show(this.getContentPane(), "cardAffPat");  
    }//GEN-LAST:event_jMenuItemAffActionPerformed

    private void jMenuItemRechNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRechNumActionPerformed
        cl.show(this.getContentPane(), "cardRechNumPat");
    }//GEN-LAST:event_jMenuItemRechNumActionPerformed

    private void jMenuItemRechNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRechNomActionPerformed
        cl.show(this.getContentPane(), "cardRechNomPat");
    }//GEN-LAST:event_jMenuItemRechNomActionPerformed

    private void jMenuAffPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAffPresActionPerformed
        cl.show(this.getContentPane(), "cardAffPres");
    }//GEN-LAST:event_jMenuAffPresActionPerformed

    private void jMenuRechNumPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRechNumPresActionPerformed
        cl.show(this.getContentPane(), "cardRechNumPres");
    }//GEN-LAST:event_jMenuRechNumPresActionPerformed

    private void jMenuRechPatPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRechPatPresActionPerformed
        cl.show(this.getContentPane(), "cardRechPatPres");
    }//GEN-LAST:event_jMenuRechPatPresActionPerformed

    private void jMenuCreaPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreaPresActionPerformed
        cl.show(this.getContentPane(), "cardCreaPres");
    }//GEN-LAST:event_jMenuCreaPresActionPerformed

    private void jMenuCreaMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreaMedocActionPerformed
        cl.show(this.getContentPane(), "cardCreaMedoc");
    }//GEN-LAST:event_jMenuCreaMedocActionPerformed

    private void jMenuRechNumMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRechNumMedocActionPerformed
        cl.show(this.getContentPane(), "cardRechNumMedoc");
    }//GEN-LAST:event_jMenuRechNumMedocActionPerformed

    private void jMenuRechDescMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRechDescMedocActionPerformed
        cl.show(this.getContentPane(), "cardRechDescMedoc");
    }//GEN-LAST:event_jMenuRechDescMedocActionPerformed

    private void jMenuAffMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAffMedocActionPerformed
       cl.show(this.getContentPane(), "cardAffMedoc");
    }//GEN-LAST:event_jMenuAffMedocActionPerformed

    private void jMenuAffQuantMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAffQuantMedocActionPerformed
        cl.show(this.getContentPane(), "cardAffQuantMedoc");
    }//GEN-LAST:event_jMenuAffQuantMedocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pharmacie.graph.AffMedoc affMedoc;
    private pharmacie.graph.AffPatient affPatient;
    private pharmacie.graph.AffPrescription affPrescription;
    private pharmacie.graph.AffQuantMedoc affQuantMedoc;
    private pharmacie.graph.CreaMedicament creaMedicament;
    private pharmacie.graph.CreaPatient creaPatient;
    private pharmacie.graph.CreaPrescription creaPrescription;
    private javax.swing.JMenuItem jMenuAffMedoc;
    private javax.swing.JMenuItem jMenuAffPres;
    private javax.swing.JMenuItem jMenuAffQuantMedoc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCreaMedoc;
    private javax.swing.JMenuItem jMenuCreaPres;
    private javax.swing.JMenuItem jMenuItemAff;
    private javax.swing.JMenuItem jMenuItemCrea;
    private javax.swing.JMenuItem jMenuItemRechNom;
    private javax.swing.JMenuItem jMenuItemRechNum;
    private javax.swing.JMenu jMenuMedoc;
    private javax.swing.JMenu jMenuPat;
    private javax.swing.JMenu jMenuPres;
    private javax.swing.JMenuItem jMenuRechDescMedoc;
    private javax.swing.JMenuItem jMenuRechNumMedoc;
    private javax.swing.JMenuItem jMenuRechNumPres;
    private javax.swing.JMenuItem jMenuRechPatPres;
    private pharmacie.graph.RechMedocDesc rechMedocDesc;
    private pharmacie.graph.RechMedocNum rechMedocNum;
    private pharmacie.graph.RechPatNom rechPatNom;
    private pharmacie.graph.RechPatNum rechPatNum;
    private pharmacie.graph.RechPresNum rechPresNum;
    private pharmacie.graph.RechPresPat rechPresPat;
    // End of variables declaration//GEN-END:variables
}
